### ISSUE TITLE
Invalid resource ID's doesn't always return a 404

### ISSUE THREAD

**Issue by Prouser123** [SpiGetOrg/api.spiget.org#2]
When using the endpoint of `api.spiget.org/v2/resources/1`, it will return a code 404 as expected, as 1 is not a valid resource id.

However, when using the endpoints `http://api.spiget.org/v2/resources/1/versions` or `http://api.spiget.org/v2/resources/1/versions/latest` it returns `[]` and `null` respectively, but still returns an HTTP status code of 200. (OK)

**Comment by InventivetalentDev** [comment]
Should now return 404 for those endpoints.
