### ISSUE TITLE
Webhook register not working

### ISSUE THREAD

**Issue by Lenni0451** [SpiGetOrg/api.spiget.org#3]
When ever I'm trying to register a Webhook the Server rejectes the request and does not register it.

Response Body:
```json
{
  "error": "Unexpected Exception",
  "msg": "Unexpected Exception. Please report this to https://github.com/SpiGetOrg/api.spiget.org/issues"
}
```

Response Code:
```
500
```

Response Headers:
```json
{
  "content-type": "application/json; charset=utf-8",
  "content-length": "144"
}
```

It would be nice if you could resolve this issue.

**Comment by InventivetalentDev** [comment]
What are you using to register it?

**Comment by Lenni0451** [comment]
It tried it with the api and the https://spiget.org/webhook/ site.

**Comment by Lenni0451** [comment]
The Webhook seems to work now after clicking on ```Connection failed. Status code: -1 | If you are sure it will work anyway, click here``` on the https://spiget.org/webhook/ site.
But it does not work with the direct api because there is no "force mode".

**Comment by InventivetalentDev** [comment]
You don't need a "force mode", that is done entirely on the client side of that web page. You likely had an error in the API request you sent.
